# Generated by Django 3.0.5 on 2020-05-26 08:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200526_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
