# Generated by Django 3.0.5 on 2020-05-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20200526_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%D'),
        ),
    ]
