# Generated by Django 3.0.5 on 2020-05-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_info_id_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='phone',
            new_name='contact_no',
        ),
    ]
