# Generated by Django 3.0.5 on 2020-05-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200526_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='contact_no',
            field=models.TextField(blank=True),
        ),
    ]
