# Generated by Django 3.0.5 on 2020-05-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20200526_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
